channels:
  - ome
  - conda-forge
  - joshmoore
  - defaults
  - anaconda
dependencies:
  - python==3.9.0
  - ipython==7.22.0
  - wheel==0.36.2
  - requests==2.25.1
  - h5py==3.2.1
  - s3fs==0.6.0
  - scikit-image==0.18.1
  - scipy==1.6.2
  - xarray==0.17.0
  - zarr==2.7.1
  - go-mc==2020.11.17
  - pip==21.0.1
  - pytest-benchmark==4.0.0
  - pytest-csv==2.0.2
  - pytest-profiling==1.7.0
  - seaborn==0.11.1
  - ptitprince==0.2.5
  - pip:
      - PyQT5==5.13.1
      - ome-zarr==0.0.17
      - awscli==1.19.49
      - boto3==1.17.49
